# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54fe118ee19adb88e318952a8b7060876f08f52cfdddeda11aa4e65e7ac7ffa257d94dbf7c2cb4592bb95043b5969cb3e494b908e7e73ee801772043487b2d1c

test:
  secret_key_base: c9455b2153d45b19b9e2a2eebc4c2bfb9cbf63e1e017d09b03263b7a38d28a13e8a4ffbba4e244ad4c37d1417e80f8fc93721d5af388992c1b204d506c83e446

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
